name: 'Terraform Plan'

on:
  push:
    branches:
      - master

env:
  #YA_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #YA_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #YA_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_github_password: ${{ secrets.CUSTOM_PAT }}

jobs:

  infra_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        #working-directory: ./infrastructure

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.8

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init >> $Env:GITHUB_OUTPUT

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color >> $Env:GITHUB_OUTPUT

    #- name: Terraform Plan
    #  id: plan
    #  run: terraform plan -out ${{ inputs.terraform-plan-artifact-name }}terraform plan -out ${{ inputs.terraform-plan-artifact-name }} -detailed-exitcode || true >> $Env:GITHUB_OUTPUT
    #  continue-on-error: False
