name: 'Terraform Plan'

on:
  push:
    branches:
      - master


env:
  TF_VAR_YC_FOLDER_ID: ${{ secrets.YA_FOLDER_ID }}
  TF_VAR_YC_CLOUD_ID: ${{ secrets.YA_CLOUD_ID }}
  TF_VAR_YC_TOKEN: ${{ secrets.YA_TOKEN }}


jobs:

  infra_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_PAT }}
        ref: ${{ github.head_ref }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.8

    #- name: Terraform Format
    #  id: fmt
    #  run: terraform fmt -recursive -check >> $Env:GITHUB_OUTPUT

    - name: Terraform Init
      id: init
      run: terraform init >> $Env:GITHUB_OUTPUT

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color >> $Env:GITHUB_OUTPUT

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: False

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"