name: 'Terraform Plan'

on:
  push:
    branches:
      - master

env:
  #YA_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #YA_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #TF_VAR_token: ${{ secrets.YA_TOKEN }}
  #TF_VAR_cloud_id: ${{ secrets.YA_CLOUD_ID }}
  #TF_VAR_folder_id: ${{ secrets.YA_FOLDER_ID }}
  #TF_VAR_github_password: ${{ secrets.CUSTOM_PAT }}
  TF_VAR_YC_FOLDER_ID: ${{ secrets.YA_FOLDER_ID }}
  TF_VAR_YC_CLOUD_ID: ${{ secrets.YA_CLOUD_ID }}
  TF_VAR_YC_TOKEN: ${{ secrets.YA_TOKEN }}


jobs:

  infra_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.8

    #- name: Terraform Format
    #  id: fmt
    #  run: terraform fmt -recursive -check >> $Env:GITHUB_OUTPUT

    - name: Terraform Init
      id: init
      run: terraform init >> $Env:GITHUB_OUTPUT

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color >> $Env:GITHUB_OUTPUT

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false -detailed-exitcode || true >> $Env:GITHUB_OUTPUT
      continue-on-error: False
